version: '3.8'

services:
  backend_service:
    image: example-backend:1.14
    ports:
      - 8080:8080
    container_name: backend
  
  frontend_service:
    image: example-frontend:1.14
    ports:
      - 5000:5000
    container_name: frontend