version: '3.8'

services:
  redis_service:
    image: redis
    container_name: redis

  backend_service:
    image: example-backend
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis_service
    container_name: backend

  frontend_service:
    image: example-frontend
    ports:
      - 5000:5000
    container_name: frontend